version: "3.9"

services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "crynux_relay"
      MYSQL_USER: "crynux_relay"
      MYSQL_PASSWORD: "crynuxrelaypass"
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - crynux-e2e-net

  crynux-node:
    image: crynux-node:e2e
    container_name: crynux-node-e2e
    restart: unless-stopped
    volumes:
      - ./node/config:/app/config
      - ./node/db:/app/db
      - ./node/logs:/app/logs
      - ./node/tmp:/app/tmp
    networks:
      - crynux-e2e-net
    ports:
      - "7412:7412"
    # TODO: Add GPU options if required by host.

  crynux-relay:
    image: crynux-relay:e2e
    container_name: crynux_relay
    restart: unless-stopped
    volumes:
      - ./relay/config:/app/config
      - ./relay/data:/app/data
    ports:
      - "18080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - crynux-e2e-net

  crynux-relay-wallet:
    image: crynux-relay-wallet:e2e
    container_name: crynux-relay-wallet-e2e
    restart: unless-stopped
    depends_on:
      - crynux-relay
    volumes:
      - ./relay-wallet/config:/app/config
      - ./relay-wallet/data:/app/data
    networks:
      - crynux-e2e-net

  crynux-bridge:
    image: crynux-bridge:e2e
    container_name: crynux-bridge-e2e
    restart: unless-stopped
    depends_on:
      - crynux-node
      - crynux-relay
    volumes:
      - ./bridge:/app/data
    ports:
      - "8080:8080"
    networks:
      - crynux-e2e-net
    # TODO: Confirm Bridge API port and startup command.

networks:
  crynux-e2e-net:
    name: crynux-e2e-net
    driver: bridge
